### ISSUE TITLE
Tracking issue for 2i2c using MyST to generate a report

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1002]
We decided to use the new MyST build engine to create a three-year CZI report and retrospective, hosted at the following link:

https://2i2c.org/report-czi-2021

This is a tracking issue for the things that came up during that effort. I'm putting it into this style of an issue in order to track a pattern we hope to follow more times, which is to:

1. Work with a community to convert their Jupyter Book content into MyST
2. Identify the confusion points, missing functionality, etc and track them as issues for development
3. Resolve the issues and then re-deploy to the new book

### Issues uncovered

- [x] https://github.com/executablebooks/mystmd/pull/961
- [x] https://github.com/executablebooks/myst-theme/issues/327
- [x] https://github.com/executablebooks/mystmd/issues/925
- [ ] https://github.com/executablebooks/myst-theme/issues/319
- [ ] https://github.com/executablebooks/mystmd/issues/926
- [x] https://github.com/executablebooks/mystmd/issues/947
- [ ] https://github.com/executablebooks/mystmd/issues/948
- [ ] https://github.com/executablebooks/mystmd/issues/946
- [x] https://github.com/executablebooks/mystmd/issues/1003
- [x] https://github.com/executablebooks/myst-theme/issues/332
- [ ] https://github.com/executablebooks/myst-theme/issues/331
- [ ] https://github.com/executablebooks/myst-theme/issues/326

### Documentation

- [ ] https://github.com/executablebooks/mystmd/issues/927
- [ ] https://github.com/executablebooks/mystmd/issues/966
- [x] https://github.com/executablebooks/mystmd/issues/968

### Myst website issues

- [ ] https://github.com/executablebooks/mystmd.org/issues/12
- [ ] https://github.com/executablebooks/mystmd.org/issues/13

**Comment by agoose77** [comment]
As per a discussion with Chris, we're closing this in favour of new initiatives!
