### ISSUE TITLE
Define goals and principles for the MyST document engine

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1146]
As a precursor to the Jupyter Book blog post, I think it would be helpful to define the high-level principles that guide MyST. This will make it easier to explain to others the goals and purpose of the project, and provide a foundation to help the team make decisions about what to work on. I view this as something that Jupyter Book would adopt as well.

I think that this group is already fairly-aligned on goals, principles, and values, so my hope is that this exercise is just putting them down on paper rather than creating them from scratch. I know it can be annoying to "zoom out" when there's a lot of stuff to do, so please push back if this isn't the right time, but I think it'd be valuable if we can get it done quickly!

I put together this quick starting point and put in some of my own ideas to kickstart conversation. I'd really appreciate if folks take a look at the prompts and the content, and provide edits and thoughts as you wish.

Here's a link to the document:

**[MyST strategy and goals document](https://docs.google.com/document/d/1EMMCXmua894qDiBHPXGIbM485atwc1CTkKUhigQuCG0/edit?usp=sharing)**

### Tasks

- [ ] Provide feedback and edits on the document using the prompts at the top.
- [ ] (within 1-2 weeks) converge on a minimal set of content that is "safe to try" with the core MyST team.
- [ ] Integrate this content with mystmd.org and/or put it in a blog post for #1001

**Comment by choldgraf** [comment]
I'd be happy to make time to have a call about this either in 1 on 1s or a group call, if that'd be a helpful way to talk through anything!
