### ISSUE TITLE
Tracking: Project Pythia Support

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#1320]
This is a tracking issue for Project Pythia upgrading their book to the Jupyter Book 2 / mystmd stack. It's meant to collect the major papercuts or needs for new functionality they run into along the way.

### Links

- Their new site is here: https://projectpythia.org/
- GitHub org: https://github.com/projectpythia-mystmd
- Julia Kent talk at JupyterCon 2025: https://www.youtube.com/watch?v=SqmMoyqSU8o

### Highlighted workflow

@agoose77, myself as well as @fwkoch and @stevejpurves (in the background of the conference) were helping out from the EBP core team. It was **very very** exciting to see the progress that the team was able to make on bringing together a full workflow from landing pages to all of the cookbooks that the community creates. The exciting features that we highlighted were:

- the ability to centralize configuration for the entire project (via the new inheritance @fwkoch worked on recently #1215)
- the ability to cross-reference content between their "foundations" content into the other projects (via #1180, last month)

https://github.com/executablebooks/mystmd/assets/913249/5050301f-e17c-4dd2-bfbd-f0806645e78f

There were also examples of creating plugins via python and galleries by @agoose77 and @jmunroe, based in part on my [prototyping here](https://github.com/berkeley-scf/course-site-myst/pull/3) a while back.

![image](https://github.com/executablebooks/mystmd/assets/913249/aecd9527-b92a-49c4-888e-b07f157488e4)

The infrastructure group talked about limitations of the current stack that are blocking adoption, as well as UX papercuts and UI improvements that we should prioritize.

### List of improvements and features they'd like

- [x] Write a blog post about the week 📖 https://github.com/executablebooks/meta/pull/1192
- [x] Logos (light and dark mode inherited) #1296 
- [x] Add tags to project frontmatter #1289
- [x] Favicon needs to work on static sites #1296 
- [ ] https://github.com/jupyter-book/myst-theme/issues/362
- [x] Nav logo URL needs to be configurable (right now it points to root site) https://github.com/jupyter-book/myst-theme/pull/620
- [x] Copyright info at the bottom of the page (possible with footers: https://github.com/jupyter-book/mystmd/issues/1920)
- [x] Footer (including the double footer concept) https://github.com/jupyter-book/myst-theme/pull/565
- Banners for landing page
  - [x] If "banner" means a notification banner, fixed by https://github.com/jupyter-book/myst-theme/issues/509
  - [x] If "banner" means a wide landing image, fixed by https://github.com/jupyter-book/myst-theme/pull/531
  - If "banner" means a featured-image style thing, this: https://github.com/jupyter-book/mystmd/issues/2092 
- [ ] https://github.com/jupyter-book/myst-theme/issues/639
- [x] #1298 
- [x] #100 (could be algolia to start with potentially)
- [ ] https://github.com/jupyter-book/myst-theme/issues/640
- [ ] Launch buttons #1235 (buttons need improved UX and the launch doesn’t get you to the right notebook internally) https://github.com/jupyter-book/mystmd/issues/1235
- [ ] https://github.com/jupyter-book/jupyter-book/issues/900

I would like to encourage folks from ProjectPythia to jump in here and add anything else that we are missing and ways that we can help support you. :)

cc @jukent @kafitzgerald @brian-rose @dcamron @mgrover1 @ktyle @anissa111 @matakleo @jmunroe @jnywong

**Comment by choldgraf** [comment]
We need to write a blog post about this

**Comment by brian-rose** [comment]
I'm not sure how in-scope this is here, but one key feature of the existing Pythia infrastructure is the ability to route notebook execution to an arbitrary Binder service at build time (for context, see [this Pangeo Discourse post](https://discourse.pangeo.io/t/statement-of-need-integrating-jupyterbook-and-jupyterhubs-via-ci/2705)).

We got this working for Pythia Cookbooks with an ugly hack of the `jupyterbook build` command on GitHub Actions, see [here](https://github.com/ProjectPythia/cookbook-actions/blob/0c3c3f6c5aac2f546101c9667f43b6a25765b7be/.github/workflows/build-book.yaml#L228).

Support for a more flexible separation between the computational environments for the book build and the notebook code execution would be very very useful for Project Pythia, and presumably for a much broader community as well.

**Comment by rowanc1** [comment]
Hi all -- the blog post from ExecutableBooks is here:

https://executablebookproject--1192.org.readthedocs.build/en/1192/blog/2024-06-14-project-pythia-mystmd/

The PR is if you have any further edits:
https://github.com/executablebooks/meta/pull/1192

Aiming to get that out early this week! Thanks @agoose77 and @brian-rose for feedback on the blog!

**Comment by rowanc1** [comment]
Hi all - the ExecutableBooks blog is live:
https://executablebooks.org/en/latest/blog/2024-06-14-project-pythia-mystmd/

**Comment by dcamron** [comment]
#1323 for a.) the option to flatten nested glob'd notebooks in the toc and b.) converting existing patterns in the upgrade process is potentially big for a few specific Cookbooks' use-cases

**Comment by dcamron** [comment]
Support for `.. bibliography::` style rendering of a full list of citations across an entire book/from a single bibtex would be valuable for multiple Cookbooks.

**Comment by bsipocz** [comment]
I'm looking at the list and wonder if we could close this issue?  I think a few of the not yet ticked out items got addressed, too, and for the remaining ones maybe it's more productive at this point to open up individual issues instead, especially as some of them are myst-theme related and some of them are big impactful feature requests that are deserved to be not burried into a list here (e.g. the gallery filtering)

**Comment by dcamron** [comment]
I support that. I will check with the other Pythia folks though. I think we need the nudge to review and reindex needs on our side anyway.

**Comment by choldgraf** [comment]
I suggest we do a quick pass at the list above, and:

- If an issue exists that tracks it, replace the item with a link to that issue (closed or open)
- For ones without an issue, open an issue so we're tracking it

That way in the future, we can have an internal link in github that shows us which issues are important to Pythia either way

**Comment by choldgraf** [comment]
I've gone through and linked issues that I could find, related to the items that were there. Most of them are completed, though it wasn't always clear what exactly we meant by the list items (e.g. "banner" can mean many things). Feel free to edit that list!

I think we could safely close this issue, though some of these would be pretty quick to improve. I bet the "expose tags via metadata" could be a little myst plugin that used similar logic to https://jupyter-book.github.io/myst-plugins/update-date/ . I think the social media contact links would be super quick to implement.

That said, for now I'm focused on bugfixes so I want to make sure we stabilize the big problems people are running into before spending time on new functionality. I am more than happy to review work or discuss with folks that want to tackle the others

**Comment by dcamron** [comment]
Poking here for visibility and potential advice:

As part of Cookbook creation, we exploit an ancient zenodo.org redirect `zenodo.org/badge/latestdoi/<github_api_repo_id>`. eg, for this repo, [zenodo.org/badge/latestdoi/281513508](https://zenodo.org/badge/latestdoi/281513508). **This allows us to automatically populate Zenodo DOI badges for Cookbook authors before cutting any release.** There are plenty of reasons that we may stop doing this in the future, but is really simple and convenient at the moment. If folks here have any suggestions, let us know.

Currently, [mystmd's upstream doi-utils chokes on this redirect](https://github.com/continuous-foundation/doi-utils/issues/27). Let me know if it's helpful to detail this in an issue on this repo or add any information if other issues exist.

see ProjectPythia/cookbook-gallery#27 and ProjectPythia/pythia-foundations#553

**Comment by jukent** [comment]
Similarly, I'd like to poke here on a global configuration file for how to treat external links. We have many "external" links that are to Pythia sites hosted on different GitHub repos (Foundations, the portal, the galleries, each Cookbook). The new tabs quickly become a lot.

Expected user interaction (from myst-parser): https://github.com/ProjectPythia/pythia-config/pull/22

**Comment by choldgraf** [comment]
@jukent I think that external link behavior topic is worth a dedicated issue! Would appreciate any feedback here:

- https://github.com/jupyter-book/mystmd/issues/2719
